name: Compile LaTeX document

on:
  push:
    branches:
      - main
    paths:
      - 'matt_carson_cv.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Set up TeX Live
      uses: xu-cheng/latex-action@v2
      with:
        root_file: matt_carson_cv.tex

    - name: Compile LaTeX document
      run: pdflatex matt_carson_cv.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: matt_carson_cv.pdf
        path: matt_carson_cv.pdf
