name: Build LaTeX document

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: matt_carson_cv.tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: matt_carson_cv.pdf

      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: matt_carson_cv.pdf
          asset_name: matt_carson_cv_$tag.pdf
          tag: ${{ github.ref }}
          overwrite: true
          body: "Automatic release through Github Actions"
